### ISSUE TITLE
No percentage of participants

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/meekathon#2]

**Comment by orschiro** [comment]
Can you explain?

**Comment by bloodmandarin** [comment]
27 survey entries out of 44 participants. We need to name the percentage and try to find reasons, because it is unlikely that they do the other challenges if they not do the first survey.

**Comment by orschiro** [comment]
So only 61% contribution. Do you want to add this to the README or do you want me? 

> We need to name the percentage and try to find reasons, because it is unlikely that they do the other challenges if they not do the first survey.

I would say this is a question for the final survey.

**Comment by orschiro** [comment]
Added in: https://github.com/Mindful-Meerkats/meekathon/commit/129c65579debb5fa9b19d21a022785412e8f8db1
