### ISSUE TITLE
MailChimp: Midday reminder

### ISSUE THREAD

**Issue by orschiro** [Mindful-Meerkats/meekathon#7]
Typeform feedback:

> Maybe if I could sign up for a notification sometime during the middle of the day to remind me one time (like through a text message), that might have helped me recall this. Many people like me don't check / remember / think about anything related to their personal email during working hours...

**Comment by orschiro** [comment]
As you @bloodmandarin suggested, I agree that it's a good option to:

1. Create another mailchimp list for midday reminders to which players can optionally subscribe to
2. Create new scheduled campaigns based on 1. 
3. Add the subscription link to one of the future scheduled campaigns for the next days.

**Comment by bloodmandarin** [comment]
Did you start with that already?

**Comment by bloodmandarin** [comment]
I will start now.

**Comment by orschiro** [comment]
Cool! 

Let me know whenever you want me to continue!

**Comment by bloodmandarin** [comment]
- Reminder Prompt: 
http://us9.campaign-archive2.com/?u=500e1eb1bd20ea1f4c9d20b59&id=20ef28a9e3
- Reminder Subcription Form: 
http://mindful-meerkats.us9.list-manage.com/subscribe?u=500e1eb1bd20ea1f4c9d20b59&id=c8a4976871
- Reminder Execution: 
http://us9.campaign-archive1.com/?u=500e1eb1bd20ea1f4c9d20b59&id=fdc6b3b1f3

**Comment by orschiro** [comment]
@bloodmandarin,

Wow, fantastic! 

I have replicated your midday reminder until day 10. 

Please close the issue if there is nothing to add from your side. :)

**Comment by bloodmandarin** [comment]
How do milestones work?

Shall we name the duplicates? I hope someone will enter the subscription at all. So far noone.

**Comment by orschiro** [comment]
> How do milestones work?

See slack. :) 

Source: https://guides.github.com/features/issues/#filtering

> Shall we name the duplicates?

I named the with the date of the respective day.
